# db
spring.datasource:
  url: jdbc:mysql://localhost/endpointsmonitoringservice?serverTimezone=UTC
  username: @appName@
  password: y%v2K?J~P}4rcYM$
  driver-class-name: com.mysql.jdbc.Driver

spring.jpa.hibernate.ddl-auto: validate

# liquibase
spring.liquibase.change-log: classpath:liquibase/changelog.yaml
spring.liquibase.enabled: true

# app
server.port: 8080
spring:
  application:
    name: @appName@

# swagger
swagger.enabled: true
springfox.documentation.swagger.v2.path: /@appName@/swagger/v2/api-docs

# eureka
eureka.client:
  enabled: false
  serviceUrl.defaultZone: http://127.0.0.1:8761/eureka/
  fetch-registry: true